language: android
android:
   components:
      - tools
      - platform-tools
      - build-tools-26.0.2
      - android-26
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository
sudo: false
jdk:
    - oraclejdk8
env:
    global:
      - ANDROID_TOOLS=${ANDROID_HOME}/tools
before_install:
  - nvm install 8.10.0
  - curl -L http://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip -O
  - unzip -oq android-ndk-r16b-linux-x86_64.zip
  - export ANDROID_NDK_HOME=$PWD/android-ndk-r16b
  - export PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${ANDROID_TOOLS}:${ANDROID_TOOLS}/bin:${ANDROID_HOME}/platform-tools:${ANDROID_NDK_HOME}:$PATH
  - node --version
  - gradle --version
install:
  - npm install -g npm@5.8.0
  - npm install -g cordova@8.0.0
  - npm install
  - cordova platform add android
script:
  - npm run android-stage
  - test -e platforms/android/build/outputs/apk/android-armv7-debug.apk